theme: hugo-theme-codex
title: Blabla
languageCode: en-us
baseURL: dmnkfr.github.io
copyright: Â© {year}
params:
  dateFormat: Jan 2 2006
  github: https://github.com/<your handle>
  iconOrder:
    - GitHub
    - Twitter
  showPageTitleInTOC: no
  twitter: https://twitter.com/<your handle>
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
menu:
  main:
    - identifier: about
      name: about
      title: About
      url: /
    - identifier: blog
      name: blog
      title: Blog
      url: /blog
